name: Docker Image CI for GHCR

on:
    push

jobs:
    build_and_publish:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: npm install
              run: npm ci
            - name: run the unit test
              run: npm test
            - name: Build and push the image
              run: |
                docker login --username jchung4 --password ${{secrets.ACCESS_TOKEN1}} ghcr.io
                docker build -t ghcr.io/jchung4/arithmetic-service1:latest --file Dockerfile .
                docker push ghcr.io/jchung4/arithmetic-service1:latest